// Error - Handling

// try - catch block


let a = 10;
let b = 20;
console.log("a = ",a);
console.log("b = ",b);
console.log("a+b = ",a+b);
try{
    console.log("a+b = ",a+c); 
}catch(err){
    console.log(err);
}
console.log("a+b = ",a+b);
console.log("a+b = ",a+b);
console.log("a+b = ",a+b);
console.log("a+b = ",a+b);